import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../pages/api/data.json'
import Navbar from "../components/Navbar.js"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.navigation}>
          <div className={styles.navigation_wrapper}>
            <Navbar/>

                <div className={styles.image_logo}>
                  <img src={data.logo} width={70} height={70}/>
                </div>

          </div>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.main_text}>
            <div className={styles.main_left}>
              <h1 className={styles.main_title}>
                <code className={styles.code}>{data.h1_title}</code>
              </h1>

              <p className={styles.main_description}>
                <code className={styles.code}>{data.contentText}</code>
              </p>
              <p className={styles.main_description}>
                <code className={styles.code}>{data.contentText2}</code>
              </p>
              <div className={styles.images_flex}>
               <div className={styles.image_block}>
                    <div className={styles.image_min}>
                      <img src={data.image_1}/>
                    </div>
                    <div className={styles.image_text}>
                      <code className={styles.code}>{data.image1Text}</code>
                    </div>
                </div>

                <div className={styles.image_block}>
                    <div className={styles.image_min}>
                      <img src={data.image_2}/>
                    </div>
                    <div className={styles.image_text}>
                      <code className={styles.code}>{data.image2Text}</code>
                    </div>
                </div>

                <div className={styles.image_block}>
                    <div className={styles.image_min}>
                      <img src={data.image_3}/>
                    </div>
                    <div className={styles.image_text}>
                      <code className={styles.code}>{data.image3Text}</code>
                    </div>
                </div>
              </div>
            </div>

            <div className={styles.main_right}>
              <div>
                <img src={data.image_big} width={600} height={600}/>
              </div>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Mateja Knezić
        </a>
      </footer>
    </div>
  )
}
